# Generated by Django 5.0.3 on 2024-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_healthplan_studyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='HealthPlan',
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
