# Generated by Django 4.2.11 on 2024-03-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_options_alter_user_email_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.CharField(choices=[('1', 'Week1'), ('2', 'Week2'), ('3', 'Week3'), ('4', 'Week4')], max_length=100),
        ),
    ]
